# Generated by Django 2.2.10 on 2020-05-06 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stahooServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partialoperation',
            old_name='user',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='operation_type',
        ),
        migrations.AddField(
            model_name='operation',
            name='cycle_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pending',
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(
                blank=True, related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
